### ISSUE TITLE
[Feature request] Human readable sample number in TOP VIEW

### ISSUE THREAD

**Issue by wolass** [ropensci/baRcodeR#24]
Hi! 
Thanks for this great package!

My question is if we could ask for a human-readable, short, reference number so that the person searching for samples in a cryo box would also be able to quickly visually see the contents of the QR code (which optimally would jus be part of the total barcode and put JUST UNDER the QRCODE.

This would allow us to put QR codes on top of the 1ml Epis. 

The use case that I have for it is that the QR-code with the shorter sample name goes on the top lid and the whole label (the one that is already supported) storing also the project name and additional info could be placed on the side of the epi. this does not have to be machine-readable.

In the picture below I would like to have (just the last sample number e.g. 41) visible under the QR code. 

![IMG_20200122_154240](https://user-images.githubusercontent.com/2356167/74634197-aaf4bf00-5163-11ea-8fce-c191befbd329.jpg)

The problem with the current use case is that without scanning each sample in a big cryo box we cant actually visually confirm if we are taking the proper sample. So to decrease the time needed for verification I would suggest also adding this functionality. 

Thanks again.

**Comment by wolass** [comment]
Thanks for getting back to me. 

1. I would be very interested in your reproducibility codex, is this available somewhere? Could you share which principles you follow? Or based on which publications? I think people could greatly benefit from more reproducible workflows. 

2. Your example works great, but in our lab, we often have full cryo boxes and we want to minimize the time for finding a sample. So picking each up and verifying the label on the side adds a little time to this.

3. Could I ask which label printing paper in your opinion works well enough for -80C?

4. I changed the code in your package to arrive with this you can see how I only have the patient IV and the visit number on the top view and the full label on the side. 
![IMG_20200307_124812](https://user-images.githubusercontent.com/2356167/76143117-b9ecd400-6074-11ea-9331-ed52907fbaf5.jpg)

![IMG_20200307_124826](https://user-images.githubusercontent.com/2356167/76143120-c113e200-6074-11ea-8147-1253ebf5069a.jpg)

The reasoning behind this is that all samples of similar type will be stored in the same boxes, the only variability then left is patient and visit numbers and we want to have this info quickly displayed on top. 

5. The Lab also wanted to have a date so I generate these labels using a simple shiny app. You can see it working here: https://kfo2020.shinyapps.io/Barcoding/

6. Thanks for the great package!

**Comment by ColauttiLab** [comment]
Here are answers to your questions:
1. We have a baRcodeR manuscript in review @ Methods in Ecology and Evolution. But there is also [this manuscript on biorXiv](https://www.biorxiv.org/content/10.1101/457051v1). The biorXiv pre-print is longer and includes info on PyTrackDat -- a companion python scripts for data collection and sample tracking)
2. Can you switch the orientation (see photo) or do you need the barcode on top too?
3. We use vinyl labels from ULINE (e.g. S-19297). The labels are very strong and resistant to moisture, survive -80 and even direct UV sunlight for multiple years in our field studies. One problem is the adhesive doesn't work so great so we often supplement with transparent packing tape or a clear adhesive. 
4. This is a nice modification, and I can definitely see why this would be of use! Maybe we can add this to the next official release -- would you be interested in doing a pull request since you already wrote the code?
5. This is also very nice! I wonder if we could also generalize this or add a tutorial to help others do it. Our GUI is already a shiny app, so maybe we just make that exportable as html...
6. Thanks for this great feedback -- we really enjoy hearing about different uses of the package.

![labelswitch](https://user-images.githubusercontent.com/17328412/76423243-d773b380-637c-11ea-9b63-98ac56c21f79.jpg)

**Comment by ColauttiLab** [comment]
Hi Wojiech,

I'm going to close this issue because it has come up again and we have decided to address it:
https://github.com/ropensci/baRcodeR/issues/22
